# Generated by Django 4.1.2 on 2022-10-23 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_primary_contact', models.CharField(max_length=100)),
                ('client_number_of_projects', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.TextField(max_length=200)),
                ('project_startDate', models.DateTimeField(auto_now_add=True)),
                ('project_endDate', models.DateTimeField(auto_now=True)),
                ('project_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.client')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.project')),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100)),
                ('department_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.department')),
                ('team_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.team')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
