# Generated by Django 4.1.2 on 2022-10-23 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='team_name',
            field=models.ForeignKey(default='Unassigned', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.team'),
        ),
    ]
